# Define a custom port instead of the default 8080
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:matan.p12
    key-store-password: 123456
    #key-alias: matan

security:
  require-ssl: true

logging:
  level: debug